services:
 - type: web
 name: ects-calculator
 env: python
 plan: free
 repo: https://github.com/kanweitech/fastapi_ects_calculator.git
 buildCommand: pip install -r requirements.txt
 startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

- type: web
name: ects-frontend
env: python
plan: free
repo: https://github.com/kanweitech/fastapi_ects_calculator.git
branch: main
buildCommand: pip install -r frontend/requirements.txt
startCommand: streamlit run frontend/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
